import typing
from typing_extensions import deprecated


class _CustomShaderType: ...

class _PlayerAccountManagerProtocol(typing.Protocol):
    def getFps(self) -> int: ...
    def getSoundVolume(self) -> float: ...
    def getMusicVolume(self) -> float: ...

    def setFps(self, fps: int) -> None: ...
    def setSoundVolume(self, volume: float) -> None: ...
    def setMusicVolume(self, volume: float) -> None: ...

    def loadPlayer(self, slot: int) -> None: ...
    def getCurrentPlayer(self) -> "_PlayerAccountProtocol": ...

class _PlayerAccountProtocol(typing.Protocol):
    data: dict

    def save(self) -> None: ...

    def setCutsceneAsWatched(self, cutscene_id: str) -> None: ...
    def hasPassedCutscene(self, name: str) -> bool: ...

    @property
    def coins(self) -> int: ...

    @coins.setter
    def coins(self, value: int) -> None: ...

    @property
    def rcoins(self) -> int: ...

    @rcoins.setter
    def rcoins(self, value: int) -> None: ...

    @property
    def points(self) -> int: ...

    @points.setter
    def points(self, value: int) -> None: ...

    @property
    def lives(self) -> int: ...

    @lives.setter
    def lives(self, value: int) -> None: ...

    @property
    def time_in_game(self) -> float: ...

    @time_in_game.setter
    def time_in_game(self, value: float) -> None: ...

    @property
    def passed_level_count(self) -> int: ...

    @passed_level_count.setter
    def passed_level_count(self, value: int) -> None: ...

    @property
    def current_powerup(self) -> str: ...

    @current_powerup.setter
    def current_powerup(self, value: str) -> None: ...

    @property
    def current_character(self) -> str: ...

    @current_character.setter
    def current_character(self, value: str) -> None: ...

    @property
    def current_overworld(self) -> str: ...

    @current_overworld.setter
    def current_overworld(self, value: str) -> None: ...

    @property
    def current_overworld_level(self) -> int: ...

    @current_overworld_level.setter
    def current_overworld_level(self, value: int) -> None: ...

    @property
    def unlocked_overworld_level_ls(self) -> list[str]: ...

    @unlocked_overworld_level_ls.setter
    def unlocked_overworld_level_ls(self, value: list[str]) -> None: ...


class _RequestType(typing.Protocol):
    def closeGame(self) -> None: ...
    def setTitle(self, title: str) -> None: ...
    
    @deprecated("Not implemented")
    def restartScene(self) -> None: ...
    def redirectScene(self, scene: str) -> None: ...


class _PathsType(typing.Protocol):
    def ShaderPath(self, filename: str) -> str: ...
    def AssetPath(self, filename: str) -> str: ...
    def ImagesPath(self, filename: str) -> str: ...
    def MusicPath(self, filename: str) -> str: ...
    def SoundPath(self, filename: str) -> str: ...
    def FontsPath(self, filename: str) -> str: ...
    def ShaderText(self, filename: str) -> str: ...

    def ConfigPath(self, filename: str) -> str: ...
    def CsavesPath(self, filename: str) -> str: ...

    def ConfigFolder(self, folders: str) -> str: ...
    def CsavesFolder(self, folders: str) -> str: ...
    
    def findGlobal(self, folder: str, file_category: str) -> list[str]: ...


class _AssetsType(typing.Protocol):
    def pushAtlas(self, atlas_key: str, atlas_path: str) -> None: ...
    def pushFont(self, font_key: str, font_path: str) -> None: ...

    
    def regSound(self, sound_key: str, sound_path: str) -> None: ...
    def regMusic(self, music_key: str, music_path: str) -> None: ...

    def regImage(self, texture_key: str, texture_path: str, texture_filter: int=0, texture_anisotropy: int=0) -> None: ...
    def regCutOutImage(self, texture_key: str, atlas_key: str, x: int, y: int, w: int, h: int, texture_filter: int=0, texture_anisotropy: int=0) -> None: ...

    def regShader(self, shader_key: str, your_shader: _CustomShaderType) -> None: ...

    def _regRawImage(self, texture_key: str, texture: typing.Any) -> None: ...

    
    def delSound(self, sound_key: str) -> None: ...
    def delMusic(self, music_key: str) -> None: ...

    
    def delImage(self, texture_key: str) -> None: ...
    
    def delShader(self, shader_key: str) -> None: ...


class _SoundType: 
    def play(loops: int=0, start: int=0, fade_ms: int=0) -> None: ...

class _StreamType:
    def pause(self) -> None: ...
    def unpause(self) -> None: ...

    def stop(self) -> None: ...
    def play(self, starts: int=0, loops: int=0, fade_in: int=0) -> None: ...
    def load(self, music_key: str) -> None: ...
    def fadeOut(self, fadeout: int) -> None: ...
    def setVolume(self, volume: float) -> None: ...
    def giveSound(self, sound_key: str) -> _SoundType: ...



class _RendererType:
    def render(self, 
               texture_key: str, 
               *, 
               size: tuple=(1, 1), 
               position: tuple=(0, 0), 
               r: float=1.0,
               g: float=1.0,
               b: float=1.0,
               a: float=1.0,
               layer: int=1,
               flx: bool=False,
               fly: bool=False,
               shader_key: str="default",
               mode: int=0
               ) -> None: ...



class Evalent(typing.Protocol):
    type: typing.Any
    key: int


class GameType(typing.Protocol):
    delta_time: float
    
    width: int
    height: int

    renderer: _RendererType

    request: _RequestType
    paths: _PathsType
    assets: _AssetsType
    account: _PlayerAccountManagerProtocol
    audio: _StreamType

    settings_read: dict

    def getFps(self) -> float: ...
    def getScene(self) -> str: ...
    def clearColor(self, r: float, g: float, b: float) -> None: ...

