import typing
from typing_extensions import deprecated


class CustomShaderType: ...


class _RequestType(typing.Protocol):
    def closeGame(self) -> None: ...
    def setTitle(self, title: str) -> None: ...
    
    @deprecated("Not implemented")
    def restartScene(self) -> None: ...
    def redirectScene(self, scene: str) -> None: ...


class _PathsType(typing.Protocol):
    def ShaderPath(self, filename: str) -> str: ...
    def AssetPath(self, filename: str) -> str: ...
    def ImagesPath(self, filename: str) -> str: ...
    def MusicPath(self, filename: str) -> str: ...
    def SoundPath(self, filename: str) -> str: ...
    def FontsPath(self, filename: str) -> str: ...
    def ShaderText(self, filename: str) -> str: ...

    def ConfigPath(self, filename: str) -> str: ...
    def CsavesPath(self, filename: str) -> str: ...


class _AssetsType(typing.Protocol):
    def pushAtlas(self, atlas_key: str, atlas_path: str) -> None: ...
    def pushFont(self, font_key: str, font_path: str) -> None: ...

    
    def regSound(self, sound_key: str, sound_path: str) -> None: ...
    def regMusic(self, music_key: str, music_path: str) -> None: ...

    def regImage(self, texture_key: str, texture_path: str, texture_filter: int=0, texture_anisotropy: int=0) -> None: ...
    def regCutOutImage(self, texture_key: str, atlas_key: str, x: int, y: int, w: int, h: int, texture_filter: int=0, texture_anisotropy: int=0) -> None: ...

    def regShader(self, shader_key: str, your_shader: CustomShaderType) -> None: ...

    def _regRawImage(self, texture_key: str, texture: typing.Any) -> None: ...

    
    def delSound(self, sound_key: str) -> None: ...
    def delMusic(self, music_key: str) -> None: ...

    
    def delImage(self, texture_key: str) -> None: ...
    
    def delShader(self, shader_key: str) -> None: ...


class _SoundType: ...
class _StreamType:
    def pause(self) -> None: ...
    def unpause(self) -> None: ...

    def stop(self) -> None: ...
    def play(self, starts: int=0, loops: int=0, fade_in: int=0) -> None: ...
    def load(self, music_key: str) -> None: ...
    def fadeOut(self, fadeout: int) -> None: ...
    def setVolume(self, volume: float) -> None: ...
    def giveSound(self, sound_key: str) -> _SoundType: ...






class GameType(typing.Protocol):
    delta_time: float
    
    width: int
    height: int

    request: _RequestType
    paths: _PathsType
    assets: _AssetsType
    audio: _StreamType

    settings_read: dict

    def getFps(self) -> float: ...
    def getScene(self) -> str: ...
    def clearColor(self, r: float, g: float, b: float) -> None: ...

