from __future__ import annotations


class AudioEngine:
    def __init__(
        self,
        sample_rate: int = 44100,
        buffer_size: int = 512,
        channels: int = 2,
        backend: str = "miniaudio",
    ) -> None: ...

    def play(
        self,
        sound: Sound,
        volume: float = 1.0,
        pan: float = 0.0,
        speed: float = 1.0,
        paused: bool = False,
    ) -> Voice: ...

    def stop_all(self) -> None: ...
    def set_global_volume(self, volume: float) -> None: ...
    def fade_global_volume(self, target: float, time_sec: float) -> None: ...


class Sound:
    def __init__(self, path: str, loop: bool = False, volume: float = 1.0) -> None: ...

    def set_looping(self, loop: bool) -> None: ...
    def set_volume(self, volume: float) -> None: ...
    def set_lowpass(self, freq: float, resonance: float = 1.0, wet: float = 1.0) -> None: ...
    def clear_lowpass(self) -> None: ...
    def length(self) -> float: ...


class Voice:
    def stop(self) -> None: ...
    def pause(self, paused: bool = True) -> None: ...
    def set_volume(self, volume: float) -> None: ...
    def set_pan(self, pan: float) -> None: ...
    def set_speed(self, speed: float) -> None: ...
    def fade_volume(self, target: float, time_sec: float) -> None: ...
    def fade_pan(self, target: float, time_sec: float) -> None: ...
    def fade_speed(self, target: float, time_sec: float) -> None: ...
    def set_lowpass(self, freq: float, resonance: float = 1.0, wet: float = 1.0) -> None: ...
    def set_lowpass_wet(self, wet: float) -> None: ...
    def is_valid(self) -> bool: ...
    def is_paused(self) -> bool: ...
    def get_volume(self) -> float: ...
    def get_pan(self) -> float: ...
    def get_speed(self) -> float: ...
