

class BasicAccountManager:
    def getLanguage(self) -> str: ...
    def getFps(self) -> int: ...
    def getSoundVolume(self) -> float: ...
    def getMusicVolume(self) -> float: ...
    

    def setFps(self, fps: int) -> None: ...
    def setLanguage(self, language: str) -> None: ...
    def setSoundVolume(self, volume: float) -> None: ...
    def setMusicVolume(self, volume: float) -> None: ...

    def loadPlayer(self, slot: int) -> None: ...

class BasicAccount:
    coins: int
    points: int
    lives: int
    time_in_game: float
    passed_level_count: int
    current_powerup: str
    current_character: str
    current_overworld: str
    current_overworld_level: str
    current_overworld_camera_pos: list[float, float]

    def save(self) -> None: ...

    def getSlot(self) -> int: ...

    def openOverworldNode(self, node_id: str) -> None: ...
    
    def hasOverworldNodeOpened(self, node_id: str) -> bool: ...