class BasicAssets:
    def regAtlas(self, atlas_key: str, atlas_path: str) -> None: ...
    def regFont(self, font_key: str, font_path: str) -> None: ...

    
    def regSound(self, owner: str, sound_key: str, sound_path: str) -> None: ...
    def regMusic(self, owner: str, music_key: str, music_path: str) -> None: ...

    def regImage(self, owner: str, texture_key: str, texture_path: str, texture_filter: int=0, texture_anisotropy: int=0) -> None: ...
    def regCutOutImage(self, owner: str, texture_key: str, atlas_key: str, x: int, y: int, w: int, h: int, texture_filter: int=0, texture_anisotropy: int=0) -> None: ...


    def _regRawImage(self, owner: str, texture_key: str, texture) -> None: ...

    
    def delSound(self, sound_key: str) -> None: ...
    def delMusic(self, music_key: str) -> None: ...

    def delAtlas(self, atlas_key: str) -> None: ...
    def delFont(self, font_key: str) -> None: ...

    
    def delImage(self, texture_key: str) -> None: ...
    
    def delShader(self, shader_key: str) -> None: ...