class BasicAssets:
    def beginScene(self, scene_name) -> None: ...


    def regAtlas(self, atlas_key: str, atlas_path: str, persistent=False) -> None: ...
    def regFont(self, font_key: str, font_path: str, persistent=False) -> None: ...

    
    def regSound(self, sound_key: str, sound_path: str, persistent=False) -> None: ...
    def regMusic(self, music_key: str, music_path: str, persistent=False) -> None: ...

    def regImage(self, texture_key: str, texture_path: str, texture_filter: int=0, texture_anisotropy: int=0, persistent=False) -> None: ...
    def regCutOutImage(self, texture_key: str, atlas_key: str, x: int, y: int, w: int, h: int, texture_filter: int=0, texture_anisotropy: int=0, persistent=False) -> None: ...


    def _regRawImage(self, texture_key: str, texture, persistent=False) -> None: ...

    
    def delSound(self, sound_key: str) -> None: ...
    def delMusic(self, music_key: str) -> None: ...

    def delAtlas(self, atlas_key: str) -> None: ...
    def delFont(self, font_key: str) -> None: ...

    
    def delImage(self, texture_key: str) -> None: ...
    
    def delShader(self, shader_key: str) -> None: ...