class BasicSound: 
    def play(self, speed: float=1.0) -> None: ...
    def setVolume(self, volume: float) -> None: ...

class BasicAudioEngine:
    def setFilterLowPass(self, parametr: int) -> None: ...

    def pause(self) -> None: ...
    def unpause(self) -> None: ...

    def stop(self) -> None: ...
    def play(self, loop: bool=True, speed: float=1.0) -> None: ...
    def load(self, music_key: str) -> None: ...
    def fadeOut(self, ms: int) -> None: ...
    def setVolume(self, volume: float) -> None: ...
    def giveSound(self, sound_key: str) -> BasicSound: ...

