from supermarioworld.typing.runtime_type import BasicEvent


class BasicKeyboard:
    def isPressed(self, key: int) -> bool: ...
    def isDown(self, key: int, event: BasicEvent) -> bool: ...
    def isUp(self, key: int, event: BasicEvent) -> bool: ...


class BasicMouse:
    def isPressed(self) -> tuple[bool, bool, bool]: ...
    