

class BasicEvent:
    type: ...
    key: int
    y: int


class BasicSettings:
    ...


class BasicApi:
    def closeGame(self) -> None: ...
    def setTitle(self, title: str) -> None: ...
    
   
    def restartScene(self) -> None: ...
    def redirectScene(self, scene: str) -> None: ...

    @staticmethod
    def isQuiting(event: BasicEvent) -> bool: ...

    @staticmethod
    def isResized(event: BasicEvent) -> bool: ...


class BasicPath:
    def ShaderPath(self, filename: str) -> str: ...
    def AssetPath(self, filename: str) -> str: ...
    def ImagesPath(self, filename: str) -> str: ...
    def MusicPath(self, filename: str) -> str: ...
    def SoundPath(self, filename: str) -> str: ...
    def FontsPath(self, filename: str) -> str: ...
    def ShaderText(self, filename: str) -> str: ...

    def ConfigPath(self, filename: str) -> str: ...
    def CsavesPath(self, filename: str) -> str: ...

    def ConfigFolder(self, folders: str) -> str: ...
    def CsavesFolder(self, folders: str) -> str: ...
    
    def findGlobal(self, folder: str, file_category: str) -> list[str]: ...